// Package resolve exports a recording session for DaVinci Resolve: an
// ATEM-ISO-style .drp project file (Resolve imports these natively — File >
// Import Project, or double-click) and an FCPXML 1.8 file containing a true
// multicam clip. Clips are aligned by their wall-clock start timecode, so
// channels that joined a session late (auto-record) line up correctly.
//
// The .drp format is not publicly specified; the writer mirrors the files
// generated by the Blackmagic ATEM Mini ISO (reverse-engineered, see
// https://github.com/gilou/otio-drp-adapter).
package resolve

import (
	"crypto/md5"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Clip describes one finished recording of a session.
type Clip struct {
	Name        string // channel display name
	Path        string // absolute path of the media file
	W, H        int
	StartFrames int64 // start timecode as frames since midnight
	DurFrames   int64 // duration in frames
	AudioCh     int   // recorded audio channels (0 = no audio track)
}

// FramesSinceMidnight converts a wall-clock instant to a frame count for
// timecode purposes (non-drop; all supported frame rates are integer).
func FramesSinceMidnight(t time.Time, fps int) int64 {
	h, m, s := t.Clock()
	return int64((h*60+m)*60+s)*int64(fps) + int64(t.Nanosecond())*int64(fps)/int64(time.Second)
}

// Timecode formats a frame count as HH:MM:SS:FF (wrapping at 24 h).
func Timecode(frames int64, fps int) string {
	if fps <= 0 {
		fps = 30
	}
	day := int64(fps) * 24 * 3600
	frames = ((frames % day) + day) % day
	ff := frames % int64(fps)
	s := frames / int64(fps)
	return fmt.Sprintf("%02d:%02d:%02d:%02d", s/3600, s/60%60, s%60, ff)
}

// WriteProject writes "<name>.drp", "<name>.xml" (an FCP7 timeline with all
// streams stacked on separate tracks) and "<name>.fcpxml" (multicam clip)
// into dir. The clips' media files are expected to live in the same
// directory (the .drp references them by bare file name). All files are
// written even if one fails; the first error is returned.
func WriteProject(dir, name string, fps int, clips []Clip) error {
	if len(clips) == 0 {
		return errors.New("resolve: no clips to export")
	}
	return errors.Join(
		WriteDRP(filepath.Join(dir, name+"_ATEM_Project.drp"), name, fps, clips),
		WriteXMEML(filepath.Join(dir, name+"_MultiCam_Timeline.xml"), name, fps, clips),
		WriteFCPXML(filepath.Join(dir, name+"_MultiCam_Clip.fcpxml"), name, fps, clips),
	)
}

func sessionRange(clips []Clip, fps int) (start, end int64) {
	start, end = clips[0].StartFrames, clips[0].StartFrames
	for _, c := range clips {
		if c.StartFrames < start {
			start = c.StartFrames
		}
		if e := c.StartFrames + c.DurFrames; e > end {
			end = e
		}
	}
	return start, end
}

// ---------------------------------------------------------------------------
// ATEM-style .drp
//
// Line-based: the first line is a JSON header (project metadata, sources and
// the initial mixer state), each further line is a timecoded mixer event.
// The field layout below mirrors a real ATEM Mini ISO file.

type drpColor struct {
	H float64 `json:"h"`
	S float64 `json:"s"`
	L float64 `json:"l"`
}

type drpSource struct {
	Name          string    `json:"name"`
	Type          string    `json:"type"`
	Color         *drpColor `json:"color,omitempty"`
	Volume        string    `json:"volume,omitempty"`
	ProjectPath   string    `json:"projectPath,omitempty"`
	File          string    `json:"file,omitempty"`
	StartTimecode string    `json:"startTimecode,omitempty"`
	Index         int       `json:"_index_"`
}

type drpWipe struct {
	Pattern      string  `json:"pattern"`
	Symmetry     float64 `json:"symmetry"`
	XOffset      float64 `json:"xOffset"`
	YOffset      float64 `json:"yOffset"`
	Reverse      bool    `json:"reverse"`
	Softness     float64 `json:"softness"`
	BorderWidth  float64 `json:"borderWidth"`
	BorderSource int     `json:"borderSource"`
}

type drpDVE struct {
	Style      string  `json:"style"`
	Reverse    bool    `json:"reverse"`
	FillSource int     `json:"fillSource"`
	EnableKey  bool    `json:"enableKey"`
	KeySource  int     `json:"keySource"`
	Shaped     bool    `json:"shaped"`
	Clip       float64 `json:"clip"`
	Gain       float64 `json:"gain"`
	InvertKey  bool    `json:"invertKey"`
}

type drpUSK struct {
	KeyType      string  `json:"keyType"`
	OnAir        bool    `json:"onAir"`
	IsTied       bool    `json:"isTied"`
	FillSource   int     `json:"fillSource"`
	KeySource    int     `json:"keySource"`
	IsFlyKey     bool    `json:"isFlyKey"`
	IsFlying     bool    `json:"isFlying"`
	XSizePercent float64 `json:"xSizePercent"`
	YSizePercent float64 `json:"ySizePercent"`
	XPosPercent  float64 `json:"xPosPercent"`
	YPosPercent  float64 `json:"yPosPercent"`
	Index        int     `json:"_index_"`
}

type drpMEB struct {
	OnAir            bool     `json:"onAir"`
	Source           int      `json:"source"`
	TransitionActive bool     `json:"transitionActive"`
	Wipe             drpWipe  `json:"transitionWipeParameters"`
	DVE              drpDVE   `json:"transitionDVEParameters"`
	FadeToBlack      string   `json:"fadeToBlack"`
	FTBSource        int      `json:"ftbSource"`
	UpstreamKeys     []drpUSK `json:"upstreamKeys"`
	Index            int      `json:"_index_"`
}

type drpDSK struct {
	OnAir      bool   `json:"onAir"`
	IsTied     bool   `json:"isTied"`
	FillSource int    `json:"fillSource"`
	KeySource  int    `json:"keySource"`
	FaderState string `json:"faderState"`
	Index      int    `json:"_index_"`
}

type drpHeader struct {
	Version         int         `json:"version"`
	MasterTimecode  string      `json:"masterTimecode"`
	VideoMode       string      `json:"videoMode"`
	Sources         []drpSource `json:"sources"`
	MixEffectBlocks []drpMEB    `json:"mixEffectBlocks"`
	DownstreamKeys  []drpDSK    `json:"downstreamKeys"`
	RecordingID     string      `json:"recordingId"`
}

type drpEventMEB struct {
	OnAir  *bool `json:"onAir,omitempty"`
	Source *int  `json:"source,omitempty"`
	Index  int   `json:"_index_"`
}

type drpEvent struct {
	MasterTimecode  string        `json:"masterTimecode"`
	MixEffectBlocks []drpEventMEB `json:"mixEffectBlocks"`
}

// WriteDRP writes an ATEM-ISO-style project file. The session contains no
// live switching, so the event log is just the initial state (program =
// source 1) and the recording-stop event.
func WriteDRP(path, project string, fps int, clips []Clip) error {
	start, end := sessionRange(clips, fps)

	volume := driveName(path)
	if volume == "" {
		volume = "SpoutMultiRecorder"
	}

	n := len(clips)
	// Indices mirror an ATEM: 0 Black, 1..n cameras, then the synthetic
	// sources the mixer state references.
	barsIdx, color1Idx, color2Idx, mediaIdx := n+1, n+2, n+3, n+4

	sources := []drpSource{{Name: "Black", Type: "Color", Color: &drpColor{}, Index: 0}}
	for i, c := range clips {
		sources = append(sources, drpSource{
			Name:          c.Name,
			Type:          "Video",
			Volume:        volume,
			ProjectPath:   project,
			File:          baseName(c.Path),
			StartTimecode: Timecode(c.StartFrames, fps),
			Index:         i + 1,
		})
	}
	sources = append(sources,
		drpSource{Name: "Color Bars", Type: "ColorBars", Index: barsIdx},
		drpSource{Name: "Color 1", Type: "Color", Color: &drpColor{L: 1}, Index: color1Idx},
		drpSource{Name: "Color 2", Type: "Color", Color: &drpColor{H: 0.075, S: 1, L: 0.5}, Index: color2Idx},
		drpSource{Name: "Media Player 1", Type: "Still", Volume: volume, ProjectPath: project,
			StartTimecode: "00:00:00:00", Index: mediaIdx},
	)

	header := drpHeader{
		Version:        1,
		MasterTimecode: Timecode(start, fps),
		VideoMode:      fmt.Sprintf("1080p%d", fps),
		Sources:        sources,
		MixEffectBlocks: []drpMEB{{
			OnAir:  true,
			Source: 1,
			Wipe: drpWipe{Pattern: "DiamondIris", Symmetry: 0.5, XOffset: 0.5, YOffset: 0.5,
				Softness: 0.83, BorderSource: color1Idx},
			DVE: drpDVE{Style: "PushRight", FillSource: mediaIdx, EnableKey: true,
				Shaped: true, Clip: 0.5, Gain: 0.7},
			FadeToBlack: "Inactive",
			UpstreamKeys: []drpUSK{{KeyType: "Luma", FillSource: mediaIdx,
				XSizePercent: 0.2, YSizePercent: 0.2, XPosPercent: 12.5, YPosPercent: 7.0}},
		}},
		DownstreamKeys: []drpDSK{{FillSource: mediaIdx, FaderState: "Idle"}},
		RecordingID:    fmt.Sprintf("%08x", uint32(time.Now().UnixNano())),
	}

	var b strings.Builder
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(header); err != nil {
		return err
	}
	off := false
	if err := enc.Encode(drpEvent{
		MasterTimecode:  Timecode(end, fps),
		MixEffectBlocks: []drpEventMEB{{OnAir: &off}},
	}); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// ---------------------------------------------------------------------------
// FCPXML 1.8 with a multicam clip.
//
// All times are frame-exact rationals ("N/FPSs"). The multicam timeline
// starts at 0 and each angle's clip is offset by its start relative to the
// earliest clip, which is what keeps the angles in sync regardless of how
// the importer interprets tcStart.

func rational(frames int64, fps int) string {
	if frames == 0 {
		return "0s"
	}
	return fmt.Sprintf("%d/%ds", frames, fps)
}

// toSlash / baseName / driveName handle Windows paths explicitly (rather than
// via path/filepath) so the writers behave identically under `go test` on any
// OS.
func toSlash(p string) string { return strings.ReplaceAll(p, `\`, "/") }

func baseName(p string) string {
	p = toSlash(p)
	return p[strings.LastIndex(p, "/")+1:]
}

func driveName(p string) string {
	if len(p) >= 2 && p[1] == ':' {
		return p[:1]
	}
	return ""
}

func fileURL(path string) string {
	u := url.URL{Scheme: "file", Path: "/" + toSlash(path)}
	return u.String()
}

func xmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return r.Replace(s)
}

// WriteFCPXML writes an FCPXML 1.8 file with one asset per clip, a multicam
// clip whose angles are aligned by start timecode, and a project/sequence
// containing that multicam clip.
func WriteFCPXML(path, project string, fps int, clips []Clip) error {
	start, end := sessionRange(clips, fps)

	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	p(`<?xml version="1.0" encoding="UTF-8"?>`)
	p(`<!DOCTYPE fcpxml>`)
	p(`<fcpxml version="1.8">`)
	p(`  <resources>`)

	// One format resource per unique resolution.
	type dims struct{ w, h int }
	formatID := map[dims]string{}
	for _, c := range clips {
		d := dims{c.W, c.H}
		if _, ok := formatID[d]; !ok {
			id := fmt.Sprintf("r%d", len(formatID)+1)
			formatID[d] = id
			p(`    <format id="%s" frameDuration="1/%ds" width="%d" height="%d"/>`, id, fps, c.W, c.H)
		}
	}
	seqFormat := formatID[dims{clips[0].W, clips[0].H}]

	for i, c := range clips {
		uid := fmt.Sprintf("%X", md5.Sum([]byte(c.Path)))
		audio := ""
		if c.AudioCh > 0 {
			audio = fmt.Sprintf(` hasAudio="1" audioSources="1" audioChannels="%d" audioRate="48000"`, c.AudioCh)
		}
		p(`    <asset id="a%d" name="%s" uid="%s" start="%s" duration="%s" hasVideo="1" format="%s"%s src="%s"/>`,
			i+1, xmlEscape(c.Name), uid, rational(c.StartFrames, fps), rational(c.DurFrames, fps),
			formatID[dims{c.W, c.H}], audio, xmlEscape(fileURL(c.Path)))
	}

	p(`    <media id="mc1" name="%s Multicam">`, xmlEscape(project))
	p(`      <multicam format="%s" tcStart="0s" tcFormat="NDF">`, seqFormat)
	for i, c := range clips {
		p(`        <mc-angle name="%s" angleID="A%d">`, xmlEscape(c.Name), i+1)
		p(`          <asset-clip ref="a%d" name="%s" offset="%s" start="%s" duration="%s" format="%s" tcFormat="NDF"/>`,
			i+1, xmlEscape(c.Name), rational(c.StartFrames-start, fps), rational(c.StartFrames, fps),
			rational(c.DurFrames, fps), formatID[dims{c.W, c.H}])
		p(`        </mc-angle>`)
	}
	p(`      </multicam>`)
	p(`    </media>`)
	p(`  </resources>`)

	p(`  <library>`)
	p(`    <event name="%s">`, xmlEscape(project))
	p(`      <project name="%s">`, xmlEscape(project))
	p(`        <sequence format="%s" duration="%s" tcStart="0s" tcFormat="NDF">`, seqFormat, rational(end-start, fps))
	p(`          <spine>`)
	p(`            <mc-clip ref="mc1" name="%s" offset="0s" start="0s" duration="%s">`, xmlEscape(project), rational(end-start, fps))
	p(`              <mc-source angleID="A1" srcEnable="all"/>`)
	p(`            </mc-clip>`)
	p(`          </spine>`)
	p(`        </sequence>`)
	p(`      </project>`)
	p(`    </event>`)
	p(`  </library>`)
	p(`</fcpxml>`)

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// ---------------------------------------------------------------------------
// FCP7 XML (xmeml) stacked timeline.
//
// One video (and audio) track per stream, every clip placed at its offset
// from the session start, so all streams sit side by side in a single
// timeline. This is DaVinci Resolve's most reliably imported interchange
// format (File > Import > Timeline). The sequence start timecode is the
// session's wall-clock start, and every file carries its own start timecode.

func fileURLLocalhost(path string) string {
	u := url.URL{Scheme: "file", Host: "localhost", Path: "/" + toSlash(path)}
	return u.String()
}

// WriteXMEML writes the stacked-timeline FCP7 XML.
func WriteXMEML(path, project string, fps int, clips []Clip) error {
	start, end := sessionRange(clips, fps)
	total := end - start

	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	rate := func(ind string) {
		p("%s<rate><timebase>%d</timebase><ntsc>FALSE</ntsc></rate>", ind, fps)
	}
	timecode := func(ind string, frames int64) {
		p("%s<timecode>", ind)
		rate(ind + "  ")
		p("%s  <string>%s</string>", ind, Timecode(frames, fps))
		p("%s  <frame>%d</frame>", ind, frames)
		p("%s  <displayformat>NDF</displayformat>", ind)
		p("%s</timecode>", ind)
	}

	p(`<?xml version="1.0" encoding="UTF-8"?>`)
	p(`<!DOCTYPE xmeml>`)
	p(`<xmeml version="5">`)
	p(`  <sequence id="sequence-1">`)
	p(`    <name>%s</name>`, xmlEscape(project))
	p(`    <duration>%d</duration>`, total)
	rate("    ")
	timecode("    ", start)
	p(`    <media>`)
	p(`      <video>`)
	p(`        <format>`)
	p(`          <samplecharacteristics>`)
	rate("            ")
	p(`            <width>%d</width>`, clips[0].W)
	p(`            <height>%d</height>`, clips[0].H)
	p(`          </samplecharacteristics>`)
	p(`        </format>`)
	for i, c := range clips {
		rel := c.StartFrames - start
		p(`        <track>`)
		p(`          <clipitem id="v%d">`, i+1)
		p(`            <name>%s</name>`, xmlEscape(c.Name))
		p(`            <enabled>TRUE</enabled>`)
		p(`            <duration>%d</duration>`, c.DurFrames)
		rate("            ")
		p(`            <start>%d</start>`, rel)
		p(`            <end>%d</end>`, rel+c.DurFrames)
		p(`            <in>0</in>`)
		p(`            <out>%d</out>`, c.DurFrames)
		p(`            <file id="f%d">`, i+1)
		p(`              <name>%s</name>`, xmlEscape(baseName(c.Path)))
		p(`              <pathurl>%s</pathurl>`, xmlEscape(fileURLLocalhost(c.Path)))
		rate("              ")
		p(`              <duration>%d</duration>`, c.DurFrames)
		timecode("              ", c.StartFrames)
		p(`              <media>`)
		p(`                <video>`)
		p(`                  <samplecharacteristics>`)
		p(`                    <width>%d</width>`, c.W)
		p(`                    <height>%d</height>`, c.H)
		p(`                  </samplecharacteristics>`)
		p(`                </video>`)
		if c.AudioCh > 0 {
			p(`                <audio>`)
			p(`                  <samplecharacteristics>`)
			p(`                    <samplerate>48000</samplerate>`)
			p(`                    <depth>16</depth>`)
			p(`                  </samplecharacteristics>`)
			p(`                  <channelcount>%d</channelcount>`, c.AudioCh)
			p(`                </audio>`)
		}
		p(`              </media>`)
		p(`            </file>`)
		p(`          </clipitem>`)
		p(`        </track>`)
	}
	p(`      </video>`)
	hasAudio := false
	for _, c := range clips {
		if c.AudioCh > 0 {
			hasAudio = true
		}
	}
	if hasAudio {
		p(`      <audio>`)
		for i, c := range clips {
			if c.AudioCh == 0 {
				continue
			}
			rel := c.StartFrames - start
			p(`        <track>`)
			p(`          <clipitem id="a%d">`, i+1)
			p(`            <name>%s</name>`, xmlEscape(c.Name))
			p(`            <enabled>TRUE</enabled>`)
			p(`            <duration>%d</duration>`, c.DurFrames)
			rate("            ")
			p(`            <start>%d</start>`, rel)
			p(`            <end>%d</end>`, rel+c.DurFrames)
			p(`            <in>0</in>`)
			p(`            <out>%d</out>`, c.DurFrames)
			p(`            <file id="f%d"/>`, i+1)
			p(`            <sourcetrack>`)
			p(`              <mediatype>audio</mediatype>`)
			p(`              <trackindex>1</trackindex>`)
			p(`            </sourcetrack>`)
			p(`          </clipitem>`)
			p(`        </track>`)
		}
		p(`      </audio>`)
	}
	p(`    </media>`)
	p(`  </sequence>`)
	p(`</xmeml>`)

	return os.WriteFile(path, []byte(b.String()), 0o644)
}
